### ISSUE TITLE
To do:

### ISSUE THREAD

**Issue by Nico-Casarin** [DataAccess2020/class_ex_1#2]
Brief to do list:

- [x] #4
- [x]  Move .rmd to output/ 
- [x] Improve visualisation plot
- [x]  complete the report

**Comment by FCatalfamo** [comment]
I'll do now the first one!

**Comment by Nico-Casarin** [comment]
@FCatalfamo, se approvi il [pull request](https://github.com/DataAccess2020/class_ex_1/pull/6) chiudiamo anche l'ultimo punto.
