### ISSUE TITLE
Tab report

### ISSUE THREAD

**Issue by FCatalfamo** [DataAccess2020/class_ex_1#5]
Can we put the tab in the center of the page? @n-oise

**Comment by Nico-Casarin** [comment]
Ok! Provo a sistemarla. 
Nel frattempo sto facendo del rephrasing sul branch Report. Poi mando in pull request e mi dici se ti piace.

**Comment by Nico-Casarin** [comment]
Risolto in questo [commit](https://github.com/DataAccess2020/class_ex_1/pull/6/commits/8acd662ff2a1f5b7b9da8514fb7b742d33d7e393)
